import { motion } from 'motion/react'
import { MessagesSquare, Sparkles, ArrowRight, BookOpen, Layers } from 'lucide-react'

const SUGGESTIONS = [
  { text: 'What are the main concepts and findings?', icon: BookOpen },
  { text: 'Summarize the key takeaways and deadlines', icon: Sparkles },
  { text: 'Compare the methodologies discussed in the document', icon: Layers },
]

const containerVariants = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.08 } },
}

const itemVariants = {
  hidden: { opacity: 0, y: 12 },
  show: { opacity: 1, y: 0, transition: { duration: 0.35, ease: 'easeOut' } },
}

export function EmptyChatState() {
  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="show"
      className="flex flex-1 flex-col items-center justify-center p-6 text-center my-auto"
    >
      {/* 3D-style Holographic Centerpiece */}
      <motion.div
        variants={itemVariants}
        className="relative mb-6 flex h-20 w-20 items-center justify-center rounded-3xl bg-gradient-to-br from-primary-indigo/35 via-accent/25 to-primary/30 text-white border border-accent/40 shadow-[0_0_35px_rgba(229,9,20,0.3)]"
      >
        <MessagesSquare size={36} aria-hidden="true" className="text-white drop-shadow-[0_0_8px_rgba(255,30,30,0.8)]" />
        <span className="absolute -bottom-1 -right-1 flex h-4 w-4">
          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-accent opacity-75" />
          <span className="relative inline-flex rounded-full h-4 w-4 bg-accent/80 border-2 border-canvas" />
        </span>
      </motion.div>

      <motion.h2
        variants={itemVariants}
        className="font-heading text-xl font-bold tracking-tight text-foreground md:text-3xl bg-gradient-to-r from-foreground via-slate-100 to-secondary bg-clip-text text-transparent"
      >
        Ask questions about your documents
      </motion.h2>

      <motion.p variants={itemVariants} className="mt-2 max-w-md text-sm text-secondary leading-relaxed">
        Responses are generated by local Ollama (Llama 3.2:3b) and strictly grounded in your active document selection with page citations.
      </motion.p>

      {/* Suggestion Prompt Chips */}
      <motion.div variants={itemVariants} className="mt-8 flex flex-col gap-2.5 w-full max-w-md">
        <p className="text-left text-[11px] font-mono uppercase tracking-wider text-muted px-1">
          Suggested queries:
        </p>
        {SUGGESTIONS.map((suggestion, index) => {
          const Icon = suggestion.icon
          return (
            <div
              key={index}
              className="group flex items-center justify-between rounded-xl border border-line bg-surface/60 backdrop-blur-md px-4 py-3 text-left text-sm text-secondary transition-all duration-200 hover:border-line-luminous hover:bg-raised/80 hover:text-foreground hover:shadow-[0_0_20px_rgba(229,9,20,0.15)] hover:-translate-y-0.5"
            >
              <div className="flex items-center gap-3 min-w-0">
                <Icon size={16} className="text-accent group-hover:text-accent-hover transition-colors shrink-0" />
                <span className="truncate text-xs md:text-sm font-medium">{suggestion.text}</span>
              </div>
              <ArrowRight size={14} className="text-muted opacity-0 group-hover:opacity-100 group-hover:text-accent transition-all shrink-0 ml-2" />
            </div>
          )
        })}
      </motion.div>
    </motion.div>
  )
}
